### ISSUE TITLE
Highscore algorithm update

### ISSUE THREAD

**Issue by IgnasJJK** [rangewonk/LonksKits#22]
Currently, the algorithm can be slow because it has to run through the list at least twice. The new algorithm would be to start from the rank the player is on and sort in the direction (in the ranks) in which they went. The algorithm should also end when no changes were made in a check. 

Edit: This may not be a good way to do it, because it would still be called on every kill. And sometimes, multiple people might need to be reordered  in the list.

**Comment by IgnasJJK** [comment]
Alternatively, the highscores could get asynchronously reordered and only put on the board only after that has been done. Also, to waste less processing speed, the scores could only get updated every few minutes. That would slow down the update speed of the board, but there would be less lag, if any. The rank shown with the /points command might be a little inaccurate for some people.

And I just thought of this while I was writing, but the top 10 could still be updated live. If the code checked if the player who got points was on the top 10, the board could just be quickly updated to reflect on those changes.

**Comment by MnMaxon** [comment]
If you wanted to, I did this on another one of my plugins.

When a player gets/removes points, it checks if he is on the high score list.  The high score list can only contain 20 players.  If he isn't on the list, check if he has enough points to be the player ranked 20th on the list.  If he does, put him on the list, and bump the 20th player off of the list.

Then check if the player has enough points to make it into the top 10, if he was in the top ten, but he no longer has the points to remain in the top 10, update the boards with the current top 10.  If his new score is in the top 10, update the boards.

The reason why this high score list should exist, is so the plugin does not need to go through the entire yml file.

The reason why the high score list should contain 20 instead of 10 is because if a player is ranked 10, but loses some points, there is no way to check if he should remain in the top 10 without going through the entire yml and checking if someone has a higher score than them.
